queries:
  - exclude: cpp/use-of-goto
extraction:
  cpp:
    prepare:
      packages:
        - g++-11
    after_prepare:
      - export GNU_MAKE=make
      - export GIT=true
    configure:
      command:
        - cmake .
    index:
      build_command:
        - $GNU_MAKE -j`nproc` 
