version: 2

jobs:
  build:
    executor: machine
    steps:
      - checkout
      
      - run:
          name: Udpate submodules
          command: 'cd dependencies ; cmake .'
          
      - run:
          name: Compile
          command: 'make'
      - run:
          name: Run tests
          command: 'cd build ; ./test'

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                gh-pages