machine:
  timezone:
    Europe/London
  environment:
    PATH: "/home/ubuntu/cmake-3.6.2-Linux-x86_64/bin:$PATH"

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run:
          name: Udpate submodules
          command: |
            cd dependencies
            cmake .
      - run:
          name: Setup cmake and build artifacts
          command: |
            cmake .
            make -j8
      - persist_to_workspace:
          root: .
          paths: build
 # test:
 #   executor: machine
 #   steps:
 #     - attach_workspace:
 #         at: .
 #     - run:
 #         name: Execute Tests
 #         command: |
 #           cd build
 #           ./tests
 #     - store_test_results:
 #         path: build
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
