name: C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt-get update && sudo apt-get install curl libcurl4-openssl-dev

      - name: run CMake
        run: cmake . && make -j`nproc`

      - name: run tests
        run: ./scripts/run_tests.sh

#    build-windows:

#      runs-on: ${{ matrix.os }}

#      strategy:
#        matrix:
#          os: [windows-latest, windows-2016]
