name: CMake

on: [push]

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install xmllint
      run: sudo apt-get install tree curl libcurl4-openssl-dev libcurlpp-dev libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake . && make -j8

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./build/test_attachment && ./build/test_config && ./build/test_exception && ./build/test_message_constructor && ./build/test_string_util && ./build/test_task_queue
