name: MacOS cURL debug

on:
  push:
    branches:
      - feature
      - master
      - release/*
  pull_request:

jobs:
  cURL-debug:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: brew install curl

    - name: run CMake
      run: mkdir build && cd build && cmake .. -DCPP_VK_LIB_SANITIZE=1 && cmake --build . --parallel

    - name: run tests
      run: cd build/tests && ./keyboard
