name: MacOS

on: [push, pull_request]

jobs:
  build-macos:  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install curl

    - name: Run CMake
      run: |
        mkdir build &&
        cd build &&
        cmake .. -DCPP_VK_LIB_SANITIZE=1 &&
        cmake --build . --parallel

    - name: Run tests
      run: |
        cd build/tests &&
        ctest
