name: MacOS

on:
  push:
    branches:
      - feature
      - master
      - release/*
  pull_request:

jobs:
  build-macos:
  
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install deps
      run: brew install curl
      
    - name: run CMake
      run: mkdir build && cd build && cmake .. && cmake --build . --parallel
      
    - name: run tests
      run: cd build && ./build/tests
      
    - name: run benchmarks
      run: cd build && ./receiver & disown && sleep 1 && ./sender
