name: MacOS

on: [push]

jobs:
  build-macos:
  
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install deps
      run: brew install curl
      
    - name: run CMake
      run: mkdir build && cd build && cmake .. && make -j`nproc`
      
    - name: run tests
      run: cd build && make test
