name: Ubuntu cURL debug

on:
  push:
    branches:
      - feature
      - master
      - release/*
  pull_request:

jobs:
  cURL-debug:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: sudo apt-get update && sudo apt-get install curl libcurl4-openssl-dev

    - name: run CMake
      run: mkdir build && cd build && cmake .. -DCPP_VK_LIB_SANITIZE=1 && cmake --build . --parallel

    - name: run tests
      run: cd build/tests && ./curl
