name: Ubuntu

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: sudo apt-get update && sudo apt-get install curl libcurl4-openssl-dev

    - name: run CMake
      run: mkdir build && cd build && cmake .. && make -j`nproc`

    - name: run tests
      run: cd build && make test
