name: Ubuntu

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update &&
        sudo apt-get install curl libcurl4-openssl-dev

    - name: Run CMake
      run: |
        mkdir build &&
        cd build &&
        cmake .. -DCPP_VK_LIB_SANITIZE=1 &&
        cmake --build . --parallel

    - name: Run tests
      run: |
        cd build/tests &&
        ctest --verbose
