name: Windows

on: [push]

jobs:
  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [x64, x86]

    steps:
      - uses: actions/checkout@v2
        
      - name: setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: ${{ matrix.architecture }}

      - name: CMake
        run: cmake . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET="x64-windows" -G "MinGW Makefiles"

      - name: build
        run: cmake --build . --parallel 8
